import address from 'address';
import chalk from 'chalk';
import spawn from 'cross-spawn';
import * as chokidar from 'chokidar';
import clipboardy from 'clipboardy';
import createDebug, { Debugger } from 'debug';
import deepmerge from 'deepmerge';
import execa from 'execa';
import lodash from 'lodash';
import glob from 'glob';
import portfinder from 'portfinder';
import got from 'got';
import resolve from 'resolve';
import yargs from 'yargs';
import mkdirp from 'mkdirp';
import pkgUp from 'pkg-up';
import Mustache from 'mustache';
import signale from 'signale';
import rimraf from 'rimraf';
import yParser from 'yargs-parser';
import * as t from '@babel/types';
import * as parser from '@babel/parser';
import * as traverse from '@babel/traverse';
import semver from 'semver';

export { spawn };
export { semver };
export { address };
export { chalk };
export { clipboardy };
export { chokidar };
export { createDebug, Debugger };
export { deepmerge };
export { execa };
export { lodash };
export { glob };
export { got };
export { portfinder };
export { pkgUp };
export { resolve };
export { yargs };
export { mkdirp };
export { Mustache };
export { rimraf };
export { yParser };
export { t };
export { parser };
export { traverse };
export { signale };

export { default as getFile } from './getFile/getFile';
export { default as winPath } from './winPath/winPath';
export { default as winEOL, isWindows } from './winEOL/winEOL';
export { default as BabelRegister } from './BabelRegister/BabelRegister';
export { default as randomColor } from './randomColor/randomColor';
export { default as delay } from './delay/delay';