name: "All tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: "Lint and core tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test